version: '3'

services:
  icecast:
    image: vitiman/alpine-icecast:latest
    ports:
      - "8000:8000"
    networks:
      - music_stack

  mpd:
    image: vitiman/alpine-mpd:latest
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /data/music:/var/lib/mpd/music
      - /data/music_lossy:/var/lib/mpd/music/lossy

networks:
  music_stack:
    driver: bridge
